### ISSUE TITLE
Add air gap

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2536] opened 2018-10-23 19:21 UTC
3/5 of our nearly active beta users have liquids that would benefit from the air gap advanced setting.

## Acceptance criteria
- [ ] User can add an air gap to their step (transfer only?)
- [ ] When air gap is checked it generates a uL field. Just like the mix advanced setting
  - [ ] Default?
- [ ] When air gap and touch tip are checked, air gap goes first (?)

- [ ] Prevent users from using an air gap that is higher than the tip's capacity (form level and timeline level)
- [ ] Alert a user when disposal volume + air gap exceed the tip's capacity (form level and timeline level)

**Comment by umbhau** [comment] 2018-11-27 16:00
Blocked: Need to decide whether to keep order of operations in sync with API (API currently does air gap before touch tip)

**Comment by umbhau** [comment] 2018-11-30 18:17
Closing; duplicate of old #2536

**Closed by umbhau** 2018-11-30 18:17 UTC
Labels: WIP, design, feature, protocol designer
