### ISSUE TITLE
Flip Mounts

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1503] opened 2018-05-22 20:26 UTC
As a user I might not want to rebuild my protocol or change pipettes. 

## Acceptance Criteria
- Add a flip mounts button to the file page pipettes section

## Design
![image](https://user-images.githubusercontent.com/35570080/40736692-b6995d52-640c-11e8-8fec-9e1e88ff57a5.png)

**Comment by umbhau** [comment] 2018-06-08 18:46
@howisthisnamenottakenyet is this a duplicate of #1536?

**Closed** 2018-06-08 18:50 UTC
Labels: feature, medium, protocol designer
