### ISSUE TITLE
User able to view "File Details" without creating new file

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#2717] opened 2018-11-27 00:01 UTC
user should not be able to view "file details" unless a new file is created, or other file is imported.

**Comment by IanLondon** [comment] 2018-11-29 17:36
@pantslakz was this the bug where going to Settings page then back to File page would show the file details? That should be fixed

**Comment by IanLondon** [comment] 2019-01-10 15:46
Cannot reproduce in edge, I think we fixed it when refactoring `navigation` around November/December

**Closed by IanLondon** 2019-01-10 15:46 UTC
Labels: protocol designer
