### ISSUE TITLE
bug: USB Icon for Temp deck overlaps with the slot to the left of it

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5419] opened 2020-04-13 17:39 UTC
# Overview
The USB icon for the Temperature Module overlaps with the slot directly to the left of it, obscuring any labware in the slot. Perhaps this icon should be smaller and on the right.

# Current behavior
![image](https://user-images.githubusercontent.com/579696/79143701-b3e0c600-7d8b-11ea-8d78-08784c1fd84d.png)

# Steps to reproduce
1. Upload a protocol with the Temperature module in slot 3 and labware in slot 2
2. Proceed to Labware Calibration
3. Observe Slot 2

# Expected behavior
USB icon should not overlap with slot 2

**Comment by mcous** [comment] 2020-04-14 15:56
Duplicate of #4422

**Closed by mcous** 2020-04-14 15:56 UTC
Labels: app, bug, cpx
