### ISSUE TITLE
Pick-Up-Tip within UI collides with containers after 2nd click

### ISSUE THREAD

**Issue by andySigler** [Opentrons/opentrons#278] opened 2017-07-26 17:07 UTC
Seems like the calibrated position is not being considered during a robot `arc` movement only some of the time when being called from the flask server.

Steps to reproduce:

1. Load protocol with `trough-12row` and `tiprack-200uL`
2. Calibrate `trough-12row` so that it's is higher up on the Z axis than the `tiprack-200uL`
3. Press `Move-To` button on the `trough-12row` (should well well, moving up to safe height)
4. Press `Pick-Up-Tip` button on the `tiprack-200uL` (should well well, moving up to safe height)
5. Press `Move-To` button on the `trough-12row` (should well well, moving up to safe height)
6. Press `Pick-Up-Tip` button on the `tiprack-200uL`, and the pipette should move DOWNWARDS, colliding with the trough

**Comment by SimplyAhmazing** [comment] 2017-07-26 21:59
Setup above instructions and could not reproduce this bug. Validated setup with @andySigler and the bug did not re-occur on latest release for 2.5.0. Closing issue..

**Comment by andySigler** [comment] 2017-08-01 20:25
Happened again with Lucia with latest Dev build on Windows, commit #fecbde33

**Comment by astaff** [comment] 2017-09-07 03:49
Fixed in 2.5.2, @andySigler ?

**Comment by mcous** [comment] 2017-12-20 18:54
Assuming fixed and closing the issue. @andySigler please re-open if this is not the case

**Closed by mcous** 2017-12-20 18:54 UTC
Labels: bug
