### ISSUE TITLE
bug(api): delay() command log truncates seconds float to an integer

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#7066] opened 2020-12-01 16:57 UTC
# Overview

Delay() function rounds down anytime the seconds float has a decimal 

# Steps to reproduce

Create code with delay() function where either seconds had a decimal or where minutes had a decimal under 0.0167
Ran code in command window with opentrons simulate and on run app 

Example code used:
``` python
from opentrons import protocol_api
metadata = {'apiLevel': '2.7',
            'author': 'Alex '}
def run(protocol: protocol_api.ProtocolContext):
    
 tiprack_1 = protocol.load_labware('opentrons_96_tiprack_300ul',location = '1')
 p1000 = protocol.load_instrument('p300_single_gen2','left', tip_racks=[tiprack_1])
 p1000.starting_tip = tiprack_1.wells_by_name()['C1']
 p1000.pick_up_tip()
 protocol.delay(seconds = 2.4)
 p1000.drop_tip()
 p1000.pick_up_tip()
 p1000.drop_tip() 
```

# Current behavior

Displaying 2 seconds 
<img width="542" alt="2020-12-01 (2)" src="https://user-images.githubusercontent.com/74389436/100768670-2826b300-33c9-11eb-913e-de053dc0e449.png">
# Expected behavior

For delay (seconds = 2.4)
Delaying for 2.4 seconds

**Comment by mcous** [comment] 2020-12-01 18:34
Upon investigation:

- `protocol_context.delay` **delays for the correct amount of time**
- #5755 introduced a regression in the v3.19.0 release where the delay **log** truncates the float to an int, leading to an incorrect log (but correct behavior)
- The type annotations on the hardware controller for delay are wrong (marked as `int` instead of `float`), but this doesn't affect behavior because the arguments are passed through without modification

**Closed** 2020-12-02 17:45 UTC
Labels: api, bug, cpx
