### ISSUE TITLE
V2 Labware: Getter Functions for V2 Labware

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3333] opened 2019-04-10 19:33 UTC
PLACEHOLDER

Similar to #3334, will adjust size of the 2 after the fact

V1 getter functions take load name
V2 labware functions should take a pure labware object

**Comment by IanLondon** [comment] 2019-04-29 16:22
this has become a duplicate of #3334

**Closed by IanLondon** 2019-04-29 16:22 UTC
Labels: Protocol Library, app, extra-large, feature, protocol designer, shared data
