### ISSUE TITLE
5.1 Feedback:  Clear protocol button doesnot work after a prototol is run completed or cancelled - 409 conflict error appears

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10056] opened 2022-04-25 06:07 UTC
### Overview

Cancel a running protocol and then clear the protocol. 409 conflict error appears

### Current Behavior

<img width="875" alt="Screen Shot 2022-04-25 at 2 05 22 AM" src="https://user-images.githubusercontent.com/39049853/165029753-f553445b-9018-4035-9b37-d125b9ea99a6.png">

### Expected Behavior

The protocol should be cleared for the protocol to be run again.

### Steps To Reproduce

1. Upload a protocol from protocols tab
2. Goto device tab, select the device -> protocol -> run the protocol from device detail page.
3.  Cancel the run 
4. Now click on **clear protocol** button -> unable to clear protocol. 409 conflict error appears.
5. 409 error is seen when I click on clear protocol after the protocol is completed.
6. So, noticed this 409 error twice, after the protocol was cancelled and after the run complete
<img width="1345" alt="Screen Shot 2022-04-25 at 2 06 40 AM" src="https://user-images.githubusercontent.com/39049853/165029917-cba60588-8ac1-484e-ab58-53a5a03e3c36.png">

Adding the screen recording to the Ticket:
[Screen Recording 2022-04-25 at 11.45.51 AM.mov.zip](https://github.com/Opentrons/opentrons/files/8556091/Screen.Recording.2022-04-25.at.11.45.51.AM.mov.zip)

**Comment by nusrat813** [comment] 2022-04-29 18:52
@mcous - to investigate

**Comment by mcous** [comment] 2022-05-03 18:53
@reachojhaneha we've been unable to reproduce this issue, and we need the following information to investigate any further:

- The protocol used in the screen recording
- The response body of the 409 response

Additionally, the reproduction steps say the protocol should be cancelled, but the screen recording shows a protocol with the status "completed". Do you have any idea why this is the case?

**Comment by reachojhaneha** [comment] 2022-05-03 19:51
@mcous , here is the protocol used
[script_pur_sample_1.json.zip](https://github.com/Opentrons/opentrons/files/8613806/script_pur_sample_1.json.zip)

The response body of the 409 : 
{"errors":[{"id":"RunActionNotAllowed","title":"Run Action Not Allowed","detail":"Cannot modify a stopped engine."}]}

<img width="1437" alt="Screen Shot 2022-05-03 at 3 48 10 PM" src="https://user-images.githubusercontent.com/39049853/166554503-4f2db6c2-6fbc-48b1-b44a-07146be2d501.png">

Screen recording has a completed protocol, the heading of the protocol says this issue occurs when protocol is completed or cancelled. I can modify the steps, i saw this issue with cancelled protocol first and then with completed protocols also.

**Comment by mcous** [comment] 2022-05-04 19:51
@reachojhaneha that new screenshot is a different request that originally specified in the issue. The original issue notes the `PATCH /runs/:run_id`, which is triggered by the "Clear protocol" button. The new screenshot is `POST /runs/:run_id/actions`, which is triggered by the "pause" and "cancel" buttons.

This second 409 is the server correctly rejecting a request to cancel a run after it's already completed, probably due to the protocol finishing naturally just before the cancel button was clicked / cancel request was received by the robot. From an app standpoint, it looks like the client handled this rejection properly, too, and is displaying the run as completed. The "error" in the devtools is just because Chrome always logs non-2xx responses in the devtools, even if the application handled it properly.

After trying for several days, we've been unable to reproduce server rejections of the "clear protocol" button request (`PATCH /runs/:run_id`) on `edge`, using both real hardware and the simulating server. Given that this UI is apparently changing once more, I'm going to close this issue in favor of opening a new one if we encounter buggy behavior with the new UI.

**Closed by mcous** 2022-05-04 19:51 UTC
Labels: software-investigate, cpx, 5.1-feedback
