### ISSUE TITLE
Unexpected Movement after Run Cancel

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3669] opened 2019-07-02 19:13 UTC
## Expected Behavior
- After cancelling a run, robot should stop all movement. Robot should home z axis.

## Observed Behavior
- Robot continues moving after cancel is confirmed. 
- Note observed movement sometimes reflects next planned movement in protocol, and sometimes appears random

Note there is sometimes a delay after user clicks 'cancel' and before robot stops; this is okay. This bug refers to additional movement after user clicks 'confirm' in the cancel dialogue box.

## Steps to Reproduce
- Unable to reproduce this 100% of the time or find a clear pattern, but it does happen fairly often (25% of the time?)
- In general: 
  1. Start a protocol
  2. Click 'cancel'
  3. Click 'confirm'
  4. Observe robot make additional movements

**Comment by kinnari-opentrons** [comment] 2019-07-08 21:06
[protocol_for_cancel_bug.txt](https://github.com/Opentrons/opentrons/files/3370229/protocol_for_cancel_bug.txt)

**Comment by ChrisYarka** [comment] 2019-07-08 22:28
@umbhau 

Steps to reproduce this issue:
- Run the protocol Kinnari attached. Requires mag and temp decks.
- Hit cancel during the run. 

After cancelling, the robot will continue to perform additional actions. Some times the actions are normal but sometimes they will crash into seemingly random places.

**Comment by sfoster1** [comment] 2020-02-03 21:19
Duplicate of #3530

**Closed by sfoster1** 2020-02-03 21:19 UTC
Labels: api, bug, hmg
