### ISSUE TITLE
5.1 Feedback:  Help button on the bottom of the app is confusing/ doesn't work 

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#10183] opened 2022-05-02 21:25 UTC
### Overview

The help button on the bottom left of the app next to the gear is a little misleading and it doesn't open up to a new page

### Current Behavior

It does nothing when you click on it 

### Expected Behavior

It should open up to the help center/ way to contact support 

### Steps To Reproduce

Updated to 5.1 beta

Clicked on the help (?) button on the bottom left corner 

<img width="960" alt="Screenshot 2022-05-02 172356" src="https://user-images.githubusercontent.com/74389436/166330195-be44a6af-b650-431c-b060-5563a0ebd574.png">

### Operating system

Windows

### Robot setup or anything else?

Wifi connection

**Comment by nusrat813** [comment] 2022-05-11 17:15
@mikecardarelli - are we taking this button out due to the fact we won't be adding salesforce capability in 5.1.0?

**Comment by y3rsh** [comment] 2022-05-17 14:24
Closing duplicate of #10206

**Closed by y3rsh** 2022-05-17 14:24 UTC
Labels: 6.0-feedback
