### ISSUE TITLE
PD Basic Pipetting Steps: Well Selection

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#737] opened 2018-02-04 04:47 UTC
As a protocol designer, I'd like to be able to select wells/tubes/troughs for various actions.

## Acceptance Criteria
- User able to access well/trough/tube selection to set source and destination for transfer, distribute, and consolidate steps
- User able to select from mounted pipettes before selecting well/tube/trough
- User able to view well/tube/trough contents (tooltip or key?)
- User able to click and drag to highlight desired wells
- User able to enter multiple selections (e.g. for multi and single pipettes)
-- Note: How to handle click-and-drag well selection with multi-channel?
- User able to save or cancel

## Design
- Trough:
-- https://projects.invisionapp.com/share/SCFGFFDDAVX#/screens/274839589
- Well
-- https://projects.invisionapp.com/share/SCFGFFDDAVX#/screens/274839600

**Comment by IanLondon** [comment] 2018-04-26 15:06
old duplicate of #1179 and related

**Closed by IanLondon** 2018-04-26 15:06 UTC
Labels: protocol designer
