### ISSUE TITLE
autoselect wells for 1-well labware

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2006] opened 2018-08-03 14:54 UTC
As a user I'd like to be saved clicks

## Acceptance criteria
- [ ] When a user selects labware that only has 1 option for well selection (Trash, flask(?)), that well is automatically selected. That way user can skip the well selection modal.

**Comment by pantslakz** [comment] 2018-12-06 01:15
duplicate of #2708

**Closed by pantslakz** 2018-12-06 01:15 UTC
Labels: feature, protocol designer
