### ISSUE TITLE
6.0 Analytics: Hook back up the events related to running protocols

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10749] opened 2022-06-14 02:11 UTC
# Overview
A number of Mixpanel events stopped firing after the shift from 4.7.0 to 5.0.x. Let's hook them back up to the new UI  elements.

# Acceptance criteria
Make sure the following events are hooked up to the buttons on the protocol run details page: 
- [x] runStart

- [x] runFinish

- [x] runPause

- [x] runResume

- [x] runCancel

- [x] runAgain (from Protocol Run Detail Page CTA button)

- [x] runAgain (from Protocol Run Detail Page overflow menu)

**Comment by y3rsh** [comment] 2022-06-30 17:54
This is reopened as alpha.3 seems to be pushing at mixpanel but no events besides robotUpdate* are available.
This issue is blocking for the 6.0 release but not for beta.

**Comment by bndo** [comment] 2022-07-11 19:31
Closing as events were confirmed firing and in mixpanel

**Closed by bndo** 2022-07-11 19:31 UTC
Labels: 6.0-feedback, required-for-6.0

**Comment by rwarshauer** [comment] 2022-07-14 16:12
All listed buttons verified in Beta3 as working
