### ISSUE TITLE
Form-Level Error: Incompatible Labware and Pipettes

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1595] opened 2018-06-04 16:50 UTC
As a user, I would like to see an error if I'm editing a step with incompatible labware and pipettes.

## Acceptance Criteria
- If a user selects and incompatible labware and pipette, display a 'error' alert banner within the step editor
- Alert is evaluated after the following fields are not pristine: aspirate labware, dispense labware, pipette
- Error is non-dismissible
- Error does not block user from saving (more specifically: error does not affect current save logic)

## Design and Copy
- "Selected aspirate labware ${labware.name} may be incompatible with selected pipette ${pipette.name}"
- "Selected dispense labware ${labware.name} may be incompatible with selected pipette ${pipette.name}"

**Comment by umbhau** [comment] 2018-06-08 19:48
@howisthisnamenottakenyet I _think_ this is a duplicate of #1300.

**Closed** 2018-07-10 19:02 UTC
Labels: feature, protocol designer, small
