### ISSUE TITLE
Positional accuracy issues in plate loaded on magnetic module

### ISSUE THREAD

**Issue by opatel0** [Opentrons/opentrons#4046] opened 2019-09-12 15:12 UTC
## overview
Pipette fails to move to calibrated position in plate on magnetic module during run. 

## current behavior
When using a p300m for an aspirate/dispense step in a [Biorad 96 well plate](https://labware.opentrons.com/biorad_96_wellplate_200ul_pcr), there is a noticeable 1-2mm offset from the calibrated position. The offset from the center is not consistent in all wells, so compensating for this offset during labware calibration does not resolve the issue.

## steps to reproduce
Robot server/app version 3.11.4
Run a protocol with biorad well plate on magnetic module 

## expected behavior
Pipette moves reliably to the calibrated position at the center of the well

**Comment by open3dgenome** [comment] 2019-11-21 05:59
Same issue here. I noticed it since the default position of the disengaged magnetic unit is too high for my taste and beads are pulled towards the magnet when they shouldn't (e.g. while incubating for the first time with the sample).

I 3D printed an adapter so the [bio rad 96 well plate](https://labware.opentrons.com/biorad_96_wellplate_200ul_pcr) would sit higher than normally (around 5mm) and modified the protocol to fit the new engaded-height. Even after calibrating the Z-axis to its new offset the robot still goes to some sort of hard coded default the result is bent tips.

A simple control would be  to position the Z axis 20-25 cm above the magnetic unit when calibrating. In such a position, the arm should operate in the air. I tried such a setting and the robot persistently goes down to the "hard coded default" position mentioned above - completely ignoring the information learned while calibrating.

**Comment by open3dgenome** [comment] 2019-11-21 06:00
> Hey @opatel0 Can the customer provide a video of this?

I will prepare a video later today of the issue.

**Comment by open3dgenome** [comment] 2019-11-21 14:38
I updated this morning to 3.14.1 and the problem is gone. I will continue testing and report.

**Comment by bndo** [comment] 2020-01-27 21:53
Closing as presumed fix in subsequent release. Will re-open if is still occurring

**Closed by bndo** 2020-01-27 21:53 UTC
Labels: bug, hmg, needs-repro
