### ISSUE TITLE
JSON V6 Schema + Executor

### ISSUE THREAD

**Issue by shlokamin** [Opentrons/opentrons#6463] opened 2020-09-01 15:35 UTC
# Overview

There is currently no way to communicate a `Dispense Air Gap` command to the API. In PD, we manually replace all `dispenseAirGap` commands with `dispense` commands on protocol export. We need a new executor + schema with a `dispenseAirGap` command.

# Blocked

Pending discussion of whether to include `apiLevel` or not

# Implementation details

Add a dispense `dispenseAirGap` command to the new executor + schema. On the executor, it should to the same thing that `dispense` does.

# Acceptance criteria

Add the new command, review the [schema bump checklist](https://github.com/Opentrons/opentrons/pull/6285) and make sure that all criteria are fulfilled.

**Comment by IanLondon** [comment] 2020-09-08 15:24
Cross-linking: Related to #6399

**Comment by mcous** [comment] 2021-06-11 15:13
For the purposes of system alignment, we should also be discussing changes on both ends to match ProtocolEngine commands with JSON Protocol commands. Currently, there is a one-to-one mapping, so complete alignment should be technically feasible. In advance of a more full audit, currently implemented ProtocolEngine commands may be found here:

https://github.com/Opentrons/opentrons/tree/edge/api/src/opentrons/protocol_engine/commands

(As of the time of writing for this comment, the only thing to pay attention to is the payload shapes, currently named `SomeCommandRequest`). The shape of everything else is currently in flux as we simplify things to hook into the HTTP API)

**Comment by IanLondon** [comment] 2021-06-11 17:29
Duplicate of #6399

**Closed by IanLondon** 2021-06-11 17:29 UTC
Labels: :spider: SPDDRS, blocked, json protocol schema
