### ISSUE TITLE
bug: X/ Y offset in 4.2.1

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#7745] opened 2021-04-30 15:37 UTC
# Overview

An X/Y offset is seen while running protocols, despite multiple calibration attempts. 

# Steps to reproduce

Currently can't reproduce 

# Current behavior

The calibration is off a couple mm or more in the X/Y direction when the protocol is running

# Expected behavior

The protocol should run without a X/Y offset

**Comment by mcous** [comment] 2021-12-13 16:44
Closing as unable to reproduce

**Closed by mcous** 2021-12-13 16:44 UTC
Labels: bug, hmg
