### ISSUE TITLE
bug: App version 7.1 deck mapping incorrect

### ISSUE THREAD

**Issue by pkMyt1** [Opentrons/opentrons#14516] opened 2024-02-16 16:59 UTC
### Overview

In the steps and visually the app is not showing the correct deck map.  The robot is picking up tips, aspirating, and dispensing correctly but the app is reporting the wrong slot numbers.  This impacts the calibration offset check because it thinks there are tubes were we have tips.  It is also reporting the steps in use out of order. 

### Current behavior

Robot position and app call do not match.

### Expected behavior

Expect the deck map to match what is loaded and the steps to occur in order.

### Operating system

Windows

### System and robot setup or anything else?

Updated the app and robot this morning thinking it would solve the issue.  It did notl

**Comment by SyntaxColoring** [comment] 2024-02-29 18:55
Thanks for the report. We're not noticing anything like this in our own testing. Can you share a protocol file that's demonstrating the problem?

If you're not comfortable publishing it here on GitHub, I can accept it at max@opentrons.com.

**Comment by pkMyt1** [comment] 2024-03-11 18:53
I finally have time to work on this and it is worse.  I updated to 7.2.  Where does the robot get the deck layout from since v7.0?  It is trying to run a layout that does not exist.  We have always provided a template that our program reads and loads the labware appropriately.  It still loads it correctly during the analysis but when it gets to the run it is something different.  the incorrect one is always the same.  I am stuck right , need to do a run.

**Comment by pkMyt1** [comment] 2024-05-29 17:28
This appears to be the same bug reported in issue 14598.  The robot should never assume that the runs are the same.

**Comment by SyntaxColoring** [comment] 2024-05-29 18:05
Thank you for following up! I agree, #14598 could cause the symptoms you've described here.

If you don't mind, I'll close this as a duplicate of #14598 so we can focus our efforts on that one central issue. Feel free to reopen this if this turns out to be something else.

**Closed by SyntaxColoring** 2024-05-29 18:05 UTC
Labels: bug
