### ISSUE TITLE
Warning: Aspiration of more than volume in a well

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1590] opened 2018-06-04 16:05 UTC
As a user I'd like to know when i'm trying to aspirate liquid that isn't there

## Acceptance criteria
- Warning to alert user they are trying to aspirate more than current contents from well(s) in their action

## Designs
- Title: Not enough liquid in well 
- Body: You are trying to aspirate more than the current volume of one of your well(s). If you intended to add air to your tip please use the airgap advanced setting.

**Comment by umbhau** [comment] 2018-06-08 19:04
Duplicate of 1089

**Comment by umbhau** [comment] 2018-06-08 19:05
Duplicate of 1089

**Closed by umbhau** 2018-06-08 19:05 UTC
Labels: feature, protocol designer
