### ISSUE TITLE
PD: Remove the Typeform modal from PD

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4754] opened 2020-01-14 21:19 UTC
## Rationale
Remove the gating TypeForm modal since it doesn't work for some users blocking their access to PD. 

## Context
This happens eg when a user at a university that requires user login to access Internet tries to use PD, they might have to go thru the TypeForm email confirmation flow at least once a day.

**Comment by mikec116** [comment] 2020-01-14 21:33
Marking this as blocked. Not sure what the desired change is here, unless we leave this in until exiting BETA.

**Comment by umbhau** [comment] 2020-03-03 18:52
Closing as duplicate of #5126

**Closed by umbhau** 2020-03-03 18:52 UTC
Labels: blocked, protocol designer
