### ISSUE TITLE
Batch Edit Analytics Tags

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7319] opened 2021-02-11 15:06 UTC
Ticket to create analytics tags for tracking batch edit usage in Mixpanel 

At a high level, We'd like to measure:

- Usage of batch edit transfer forms (for example, by measuring save step while users are in batch edit)
- Usage of command bar tools - select/deselect, delete, duplicate, collapse)
- Which step types are users trying to batch edit? 
- Usage of Exit Batch Edit Mode button (if compared to deselect all in command bar, we can learn how customer are exiting batch edit)
- Which advanced settings are being batch edited? 
- Batch edit with labware, pipettes, etc. in common

Specifically, we're looking to add tags for the HIGH priority items in the sheet below:

See [sheet](https://docs.google.com/spreadsheets/d/1VbOgI4Z6je9xzpApmAt4foCa3z3gKdqmL3Yc6EGS74s/edit#gid=0) for detailed metrics & priority for tracking..

**Comment by shlokamin** [comment] 2021-03-15 23:13
duplicate of https://github.com/Opentrons/opentrons/issues/7403

**Closed by shlokamin** 2021-03-15 23:13 UTC
Labels: :spider: SPDDRS, protocol designer
