### ISSUE TITLE
6.0 Feedback:  35 Character renaming of a OT2 displayes outside of <div>

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10495] opened 2022-05-26 23:00 UTC
### Overview

the robot name and connection symbol should be with in the div

### Current Behavior

<img width="795" alt="Screen Shot 2022-05-26 at 6 55 56 PM" src="https://user-images.githubusercontent.com/39049853/170592876-1a16f821-6e90-4e0d-977c-886abe95a81d.png">

### Steps To Reproduce

1. Goto robot settings -> advanced
2. Rename the robot (35 character)
3. name goes out of the div

**Comment by koji** [comment] 2022-05-27 01:04
@reachojhaneha Did you use `edge`?

![Screen Shot 2022-05-26 at 9 03 52 PM](https://user-images.githubusercontent.com/474225/170608106-2dc80f23-84a7-4593-9557-b50644963dcc.png)

**Comment by reachojhaneha** [comment] 2022-05-27 01:37
@koji , i used alpha
App Software Version
6.0.0-alpha.0

**Comment by koji** [comment] 2022-05-27 18:04
@reachojhaneha thank you for your response.
From the timestamp, 6.0.0-alpha includes a long name issue solution.
As you can see, `edge` doesn't have that issue.

**Comment by reachojhaneha** [comment] 2022-06-08 17:54
Reopening this issue, as this is a regression introduced. This exists in 6.0.1-alpha

<img width="1017" alt="Screen Shot 2022-06-08 at 1 49 57 PM" src="https://user-images.githubusercontent.com/39049853/172684287-2830ab74-4989-496e-a3f3-743a12ec3a99.png">

**Comment by jerader** [comment] 2022-06-09 19:50
I am unable to reproduce this on 6.0.0-alpha.1: 

<img width="315" alt="Screen Shot 2022-06-09 at 3 50 18 PM" src="https://user-images.githubusercontent.com/66035149/172932370-7c54a381-b27c-4dfc-bfde-25dafa93af95.png">

**Comment by mikecardarelli** [comment] 2022-06-13 18:36
Closing this. We can reopen if this is reproduced somewhere other than Neha's computer

**Closed by mikecardarelli** 2022-06-13 18:36 UTC
Labels: 6.0-feedback
