### ISSUE TITLE
Pre-Protocol Labware Image does not match description

### ISSUE THREAD

**Issue by asogluizzo** [Opentrons/opentrons#7030] opened 2020-11-18 21:19 UTC
@emilywools commented on [Wed Nov 18 2020](https://github.com/Opentrons/SmoothiewareOT/issues/19)

## overview

![Screen Shot 2020-11-18 at 4.06.58 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/d36ea6fc-6cd3-4309-8fda-a86f30dcc4a4)

**Comment by mcous** [comment] 2020-11-19 05:33
Duplicate of #6178

**Closed by mcous** 2020-11-19 05:33 UTC
