### ISSUE TITLE
PD: Add generations of pipettes to Protocol Designer

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4138] opened 2019-09-30 21:37 UTC
Note: We don't currently show Gen 1 vs Gen 2 pipettes in PD, and we don't want to publicly display Gen 1 vs Gen 2 pipettes in PD until the Gen 2s start shipping (currently scheduled for 10/22). 

Visual assets: 
https://zpl.io/Vx6PZOJ

For this ticket, let's: 
- Add in the Gen 2 pipettes
- Label the existing pipettes as Gen 1
- Hide these changes behind the pre-release flag (see #4143)

See ticket #3483 for making these changes visible to the public when the Gen 2 pipettes start shipping.

**Comment by mcous** [comment] 2019-10-15 17:08
Closing as a duplicate of #3483 (implementation of pipette gen2 select in PD) and #3601 (promotion of FF'd behavior to default)

**Closed by mcous** 2019-10-15 17:08 UTC
Labels: protocol designer
