### ISSUE TITLE
Broken "Log an Issue" link

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#540] opened 2017-12-21 00:43 UTC
## overview

This is the third time I've let someone know about this and it should be incredibly easy to fix.
I've missed out on reporting 3 or 4 not small bugs in the app because the link was broken and I forgot how to reproduce them.
 

## behavior
`Log an Issue` in the `Help` menu of the app (v2.5.2) leads to a GitHub 404.
Expect it to lead here.

## steps to reproduce

Click "Log an Issue"

**Comment by mcous** [comment] 2018-05-17 19:27
This issue was caused by the transition of app development from the `OpenTrons/opentrons-app` repository to this one (`Opentrons/opentrons`).

Closing this ticket as wontfix. This bug was fixed for the [OT2](https://shop.opentrons.com/collections/ot-2-robot), and we don't have the engineering resources to backport fixes to the legacy app.

That being said, if anyone from our community would like to make updates to the legacy app, we're happy to re-open tickets and help out. The legacy version of the app lives in the `ot1-stable` branch of this repository.

**Closed by mcous** 2018-05-17 19:27 UTC
Labels: app, bug, easyfix, v2.x.x, wontfix
