### ISSUE TITLE
Pipette Multi Gen2: Add app support

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3641] opened 2019-06-27 14:40 UTC
Support Gen2 multi pipettes in frontend for both display and (if feature flag is set) change pipette. This is a placeholder for proper speccing of work from FE devs.

**Comment by mcous** [comment] 2019-10-15 17:22
Duplicate of #3597, #3630, and  #3594, which have all been addressed

**Closed by mcous** 2019-10-15 17:22 UTC
Labels: app, feature
