### ISSUE TITLE
PD: Pre-wet is skipped when multi-dispense is selected

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5001] opened 2020-02-13 22:25 UTC
# Overview

* When the **Single Transfers** motion strategy is selected, pre-wet works as expected.
* When the **Multi-Dispense** motion strategy is selected, pre-wet is skipped. It is not executed on the robot and it does not show up in the run log.

# Steps to reproduce

The attached protocol has two transfer steps. Step 1 uses Single Transfers. Step 2 uses Multi Dispense.

[Pre-Wet Test.json.zip](https://github.com/Opentrons/opentrons/files/4201540/Pre-Wet.Test.json.zip)

## Run log
```
Picking up tip from A1 of Opentrons 96 Tip Rack 300 µL on 1
Aspirating 100.0 uL from A1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dispensing 100.0 uL into A1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Aspirating 100.0 uL from A1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dispensing 100.0 uL into B1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Aspirating 100.0 uL from A1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dispensing 100.0 uL into A1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Aspirating 100.0 uL from A1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dispensing 100.0 uL into C1 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dropping tip into A1 of Trash on 12
Picking up tip from B1 of Opentrons 96 Tip Rack 300 µL on 1
Aspirating 200.0 uL from A2 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dispensing 100.0 uL into B2 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dispensing 100.0 uL into C2 of NEST 96 Well Plate 200 µL Flat on 4 at 1.0 speed
Dropping tip into A1 of Trash on 12
```

# Expected behavior

If pre-wet is enabled for a multi-dispense step, the pipette should aspirate and dispense in the source well just the same as if it were a single transfer.

**Comment by IanLondon** [comment] 2020-10-22 15:34
Duplicate of #5122

**Closed by IanLondon** 2020-10-22 15:34 UTC
Labels: :spider: SPDDRS, bug, protocol designer
