### ISSUE TITLE
bug: Cannot perform DROPTIP without a tip attached

### ISSUE THREAD

**Issue by eirinnm** [Opentrons/opentrons#10880] opened 2022-06-23 16:40 UTC
# Overview

Robot was power cycled when it had a tip attached. I can't pull them off manually. How to force the robot to drop tips?

# Steps to reproduce
Power cycle robot when it has tip attached. Connect to notebook. Run

    executor_context = execute.get_protocol_api('2.12') ## connect to robot
    p300 = executor_context.load_instrument("p300_multi_gen2", "right",)
    p300.drop_tip()

# Current behavior

    NoTipAttachedError: Cannot perform DROPTIP without a tip attached

# Expected behavior

Robot should obey my command drop tips anyway.

**Comment by mcous** [comment] 2022-06-23 18:23
Duplicate of #6243. As a workaround, you can upload a protocol that picks up a tip and then drops it and run it without physically placing a tip rack on the deck

**Closed by mcous** 2022-06-23 18:23 UTC
Labels: bug
