### ISSUE TITLE
Broken link "Log an issue" in OT app

### ISSUE THREAD

**Issue by collinedington** [Opentrons/opentrons#1102] opened 2018-03-26 22:18 UTC
In the OT app (version 2.0), `Help`->`Log and issue` links to /opentrons-app/ instead of /opentrons/ and 404s.

**Comment by mcous** [comment] 2018-03-26 23:37
Hi, thanks for filing this issue! I'm going to close it out because it's a duplicate of #540 but we're on it!

**Closed by mcous** 2018-03-26 23:37 UTC
Labels: duplicate

**Comment by collinedington** [comment] 2018-03-27 16:10
Thanks!
