### ISSUE TITLE
Y axis slow during calibration/tip probe

### ISSUE THREAD

**Issue by jshmu** [Opentrons/opentrons#1692] opened 2018-06-13 19:46 UTC
## overview
Y axis was moving slowly during calibration and tip probe (bug).

## current behavior
The single channel pipette on the right side was previously homed from another protocol. When I uploaded a new protocol and clicked calibrate tip, the pip very slowly moved towards its position for calibration. After I attached a tip and had it go to tip probe, any motion in the y-axis was much slower than it normally is. 

## steps to reproduce
opentrons-OT2P20180420A09
API 3.1.2

First uploaded  QC_protocol_300m_300s and ran it twice. Then, I uploaded 384_300s, and this issue happened for the tip probe during that protocol.

[QC_protocol_300m_300s.txt](https://github.com/Opentrons/opentrons/files/2099632/QC_protocol_300m_300s.txt)
[384_300s.txt](https://github.com/Opentrons/opentrons/files/2099633/384_300s.txt)

## expected behavior
  Y-axis should move at the normal speed/same speed as x-axis throughout calibration and tip probe.

**Comment by mcous** [comment] 2018-06-13 21:22
I was unable to reproduce this issue with the steps given above on a robot running 3.1.2. @jshmu did this issue happen more than once?

@btmorr or @andySigler do you know of anything transient off the top of your head(s) that could cause this behavior?

**Comment by mcous** [comment] 2018-09-24 19:04
Closing this issue since we couldn't repro and it's been a while. Will re-open if it is observed again

**Closed by mcous** 2018-09-24 19:04 UTC
Labels: api, investigate
