### ISSUE TITLE
Warning: volume is too specific

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1588] opened 2018-06-04 15:19 UTC
As a user I should probably be stopped from being able to put "3.333" in the volume field if the robot can't deliver that accuracy.

## Acceptance criteria
- Put a limit on decimal places for volumes with each pipette

## Design
**** We should find out what these limitations are

**Comment by umbhau** [comment] 2018-06-10 23:31
@howisthisnamenottakenyet should this be a warning, or just a field character limit?

**Comment by umbhau** [comment] 2018-06-10 23:41
@howisthisnamenottakenyet Closing this as a duplicate of #1589

**Closed by umbhau** 2018-06-10 23:41 UTC
Labels: design, feature, protocol designer
