### ISSUE TITLE
Deck Calibration Check: Tiprack Deck Setup

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#5033] opened 2020-02-20 00:41 UTC
As a user, I would like to be guided through setting up tipracks my deck for a robot calibration check.

## Acceptance Criteria
- [ ] User guided through placing tip racks on the deck
- [ ] Modal with visual guidance on placing the required 1 or 2 different tip racks
- [ ] Tiprack associated with right pipette in slot 6
- [ ] If second pipette mounted, and requires different tip, tiprack should be placed in slot 8 (if same tip, can share slot 6 tiprack)
- [ ] User can cancel and exit to home screen
- [ ] User can continue and proceed to 'Deck Calibration Check Complete' modal 

## Copy
- See design

## Design
- https://zpl.io/VD9oXxW

**Comment by sfoster1** [comment] 2020-04-29 15:57
Dupe of #5095, this is determined by the backend

**Closed** 2020-04-29 15:57 UTC
Labels: app, feature
