### ISSUE TITLE
Pipette offset from calibrated position

### ISSUE THREAD

**Issue by opatel0** [Opentrons/opentrons#3938] opened 2019-08-26 16:19 UTC
## overview
During the run of a protocol, pipettes are offset by a few mm on x/y axes from the center, even after calibrating to the center during labware calibration before the run.

## current behavior
When running a protocol, the pipette is offset from the center of a well (i.e. tip pickup, aspirate/dispense steps), even after calibrating to the center right before the run. The pipette uses this offset position for all wells of a calibrated piece of labware. For labware with conical wells, this can result in collision with the side of the well if the pipette is moving to the bottom (which can loosen the tip seal and affect accuracy). For wells with very small diameter (384 well plate), this can result in crashing with the plate outside the well.

## steps to reproduce
Robot server version: v3.10.3
Calibrate/run a python protocol using v2 labware definitions or using a Protocol Designer protocol (latest version of PD)

## expected behavior
Pipette moves reliably to calibrated point at center of well

**Comment by mcous** [comment] 2019-08-28 22:24
Is this the same issue as described in #3809?

**Comment by opatel0** [comment] 2019-08-29 16:39
It looks like #3809 is specific to the v2 10ul tiprack definition. This ticket encompasses that issue, but is more general to v2 definitions as the issue has been observed with well plates as well - next step for both issues is to reproduce issues in house.

**Comment by btmorr** [comment] 2019-10-01 14:44
@opatel0 there are some labware calibration fixes going out in 3.13.0 this week. Once it's released, can you try to reproduce the issue and update the ticket with specific info, please?

**Comment by rgatkinson** [comment] 2019-10-11 19:23
I am still seeing an issue (though it's not a _pragmatically_ large one for my own protocol, but that's mostly because I avoid going to the bottom of the well because I model the well shape and the amount of fluid therein).

I'll attach my protocol file after this comment. But what the protocol does after calibrating pipette and labware in the usual way is to pickup the same exact tip (from slot 1) that the machine just picked up and used for calibration, then move the tip to various locations on the labware to verify accuracy.

What I'm seeing consistently is that when so verifying, the locations in the plate (in slot 3) that the tip is moved to are to the left (W) and down (S) from what I had just very carefully calibrated them to be, maybe by 0.5mm and 1mm respectively. I can see no obvious reason for such a discrepency. FWIW, I just recalibrated my deck yesterday.

'Frustating, though at least I can deal with it. Others who move the tip often to the bottom of wells may not be so lucky.

**Comment by rgatkinson** [comment] 2019-10-11 19:25
[pairwise_master.zip](https://github.com/Opentrons/opentrons/files/3719340/pairwise_master.zip)

**Comment by wolfrickw** [comment] 2019-10-12 06:57
There might be a problem with the 'opentrons_24_tuberack_nest_1.5ml_snapcap' well spacing X values.
Right after labware calibration the tip will point to the center position of a the wells in column 1 (A1, B1 etc) after executing pipette300.move_to(mix_rack1.well("A1").top()), but will almost hit the left side of rims in column 6 (A6, etc.). Y spacing seems to be more or less OK. The slot used for tuberack is 4, software ver, is 3.13.0. For the Opentrons 96 Well Aluminum Block with Generic PCR Strip 200 µL the same tip is aligned fine to all of the edge positions  (slot 3).
![rack1](https://user-images.githubusercontent.com/55856056/66696631-f4bd2c80-eccd-11e9-8905-ef1ae784874f.jpg)

**Comment by SyntaxColoring** [comment] 2019-10-28 21:21
The `opentrons_24_tuberack_nest_1.5ml_snapcap` issue above is separate; see #4238.

#4288 is a cause of this issue, but it is specific to tip racks.

**Comment by SyntaxColoring** [comment] 2020-02-10 22:27
We're closing this ticket in favor of tracking these issues with more specificity. See #4238 and #4288 as examples.

As far as we know, there's no outstanding software bug that accidentally adds an offset to pipette position.

If you run into something that looks like this, please get in touch with Opentrons Support, and we'll help you out.

— Max Marrone, Support Engineer, Opentrons Labworks

**Closed by SyntaxColoring** 2020-02-10 22:27 UTC
Labels: bug, hmg, needs-repro
