### ISSUE TITLE
PD Liquid Tracking: Highlight Wells and Labware in a Step

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#962] opened 2018-03-03 20:44 UTC
As a protocol designer, I'd like to see the which wells are involved in a step

## Acceptance Criteria
- When user hovers over a step
-- Highlight source and destination wells
-- Highlight involved labware

* This only applies to an actively hovered (not clicked-to-be-selected) step. When not hovering over a step, labware/wells are not highlighted.

* This story does not include the mouseover/popover, or the color-coded ingredient names, from the image below.

## Dependencies
- #1083 
- How might we handle large transfers (above pipette capacity)

## Design
- @howisthisnamenottakenyet: 
-- Assuming this should be on hover, not on click
^^It's on hover not on click because in the future we intend to use clicking to edit the well or volume right in the side panel. Will allow for things like a distribute with different dispense volumes across one action. 
![image](https://user-images.githubusercontent.com/35570080/36981799-13b50684-205c-11e8-94fa-8d49e13fdee0.png)

**Comment by IanLondon** [comment] 2018-03-23 16:10
I labeled this as `blocked` b/c it's too big to be actionable

#1083 addresses part of this

**Comment by umbhau** [comment] 2018-03-26 02:47
@IanLondon updated this story to include 'step' only, and not 'sub-step'

**Comment by IanLondon** [comment] 2018-04-05 19:00
After paring this ticket down, it became a duplicate of #1083

**Closed by IanLondon** 2018-04-05 19:00 UTC
Labels: blocked, design, extra-large, protocol designer
