### ISSUE TITLE
6.0 Feedback:  Protocols page footer

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10793] opened 2022-06-16 13:48 UTC
### Overview

the protocols page footer has inconsistent link styling. see screenshot. the link to `Open Python API Documentation` is the hover state as the off state. 

the 3 links also need more space between them. see figma for the right spacing. 
![Screen Shot 2022-06-16 at 9 46 23 AM](https://user-images.githubusercontent.com/4339860/174084311-af6d4095-6254-4781-b047-c23aae7a695c.png)

**Comment by koji** [comment] 2022-06-16 16:13
This issue has been pointed out by Design feedback.
Will be closed by #10767

**Closed** 2022-07-18 14:14 UTC
Labels: 6.0-feedback
