### ISSUE TITLE
Protocol Designer: Use React-Router

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#907] opened 2018-02-23 17:25 UTC
As a protocol designer developer, I would like to use react router to manage pages

## Acceptance Criteria
- Protocol designer uses react router to manage file pages

## Implementation Notes
- Note we should hold on this until IA design discussion Tuesday 2/2/2018

**Comment by mcous** [comment] 2018-02-23 17:56
Duplicate of #906

**Closed by mcous** 2018-02-23 17:56 UTC
Labels: api, app, blocked
