### ISSUE TITLE
Add labware to PD labware list

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2538] opened 2018-10-23 19:24 UTC
As a user I'd like to be able to select the tube rack with 1.5mL tubes in it instead of using the 2mL definition.

## Acceptance criteria
- Add the 1.5mL tube rack definition to the PD labware library

**Comment by umbhau** [comment] 2018-10-30 14:43
@IanLondon @howisthisnamenottakenyet let's review labware list together

**Comment by IanLondon** [comment] 2018-10-30 19:09
Now a duplicate of #2582 (since 99% of the work is in adding the new definition to Python and share-data)

**Closed by IanLondon** 2018-10-30 19:09 UTC
Labels: WIP, feature, protocol designer, small
