### ISSUE TITLE
Allow moving placed labware

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1292] opened 2018-04-27 20:43 UTC
As a user I would like to be able to move placed labware. 

--

## Acceptance Criteria
-Add copy is a button on an empty slot. 
-Hovering over an occupied slot let's you choose to move the labware instead of place a copy 

## Design
![image](https://user-images.githubusercontent.com/35570080/39384201-f509d40a-4a39-11e8-97d4-848663bf4d55.png)
![image](https://user-images.githubusercontent.com/35570080/39384242-156d6720-4a3a-11e8-9b5c-a942e24e57f5.png)

**Comment by umbhau** [comment] 2018-05-02 19:08
Duplicate of 821

**Closed by umbhau** 2018-05-02 19:08 UTC
Labels: feature, protocol designer
