### ISSUE TITLE
bug: Unable to change pick up current in the Run App 

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#7305] opened 2021-02-09 20:57 UTC
# Overview

Pick up current when changed to values other than the default will give an error that says __ is invalid for the pick up current and won't allow you to save 

# Steps to reproduce

turn off __DEV__ All Pipette Config in More > App >Developer Only (Unstable)
Go to Pipette Settings
Modify plunger current 

# Current behavior

Pick up current becomes true or false  and pick up current won't save. Gives an error message. 

# Expected behavior

Pick up current should save as long as it's in the range of 0.5 to 1.2 without an error message.

**Comment by amitlissack** [comment] 2021-02-09 21:44
The issue is that `1` is interpreted as a boolean (ie True) and is assigned to a quirk. There is no recovery unless the pipette config file is modified.

**Closed** 2021-02-11 20:25 UTC
Labels: app, bug
